version: "3.6"
services:
  code-push:
    build: .
    container_name: code-push
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7.23
    container_name: mysql
    volumes:
      - data-mysql:/var/lib/mysql
      - ./sql/codepush-all.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "On"

  redis:
    container_name: redis
    image: redis:4.0.11-alpine
    volumes:
      - data-redis:/data
    # ports:
    #   - "6388:6379"

volumes:
  data-mysql:
  data-redis:
    